data:
  train_test_split_ratio: 0.2
  validation_split_ratio: 0.2
  random_state: 42

feature_engineering:
  scaling: true
  create_interaction_features: true
  features_to_use:
    - MedInc
    - HouseAge
    - AveRooms
    - AveBedrms
    - Population
    - AveOccup
    - Latitude
    - Longitude

model:
  name: lightgbm
  params:
    objective: regression
    metric: rmse
    boosting_type: gbdt
    num_leaves: 31
    learning_rate: 0.05
    feature_fraction: 0.9
    n_estimators: 100
    verbose: -1

training:
  cv_folds: 5
  early_stopping_rounds: 50 